// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzJ8jv1SuqXQrjg3IrZqRwLrXThbtiuI',
    appId: '1:245690159977:web:d89885633216e93533a3f8',
    messagingSenderId: '245690159977',
    projectId: 'nechat-70b5b',
    authDomain: 'nechat-70b5b.firebaseapp.com',
    storageBucket: 'nechat-70b5b.appspot.com',
    measurementId: 'G-JW2F8E294Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdB4vijMW7MiUTdpAOox5nc_j_txEMjQ',
    appId: '1:245690159977:android:748eb57034e33f7533a3f8',
    messagingSenderId: '245690159977',
    projectId: 'nechat-70b5b',
    storageBucket: 'nechat-70b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUUw8OZ1RLpN9HhdXxcTLH54v_0ZWFKdU',
    appId: '1:245690159977:ios:b10cfa30bbcde85a33a3f8',
    messagingSenderId: '245690159977',
    projectId: 'nechat-70b5b',
    storageBucket: 'nechat-70b5b.appspot.com',
    iosBundleId: 'com.example.neechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUUw8OZ1RLpN9HhdXxcTLH54v_0ZWFKdU',
    appId: '1:245690159977:ios:5bd9141488fe187a33a3f8',
    messagingSenderId: '245690159977',
    projectId: 'nechat-70b5b',
    storageBucket: 'nechat-70b5b.appspot.com',
    iosBundleId: 'com.example.neechat.RunnerTests',
  );
}
